# Generated by Django 4.1.5 on 2023-01-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("healthy", models.BooleanField(default=True)),
                ("type", models.CharField(max_length=30)),
                ("team", models.CharField(max_length=30)),
                ("date", models.DateField()),
            ],
        ),
    ]
