# Generated by Django 4.1.5 on 2023-01-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("healthtoad", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthrecord",
            name="date",
            field=models.DateField(unique=True),
        ),
    ]
